import category.Comic;
import category.Manga;
import category.Novel;
import category.Tale;
import category.dic;
import category.lightNovel;
import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author maMo
 */
public class MainFrame extends javax.swing.JFrame {
            
    public MainFrame() {
        initComponents();
        
    }
    
    String code = "";
    String pCode,name,YN,vol,language,keyword;
    int price,numOfBooks,rated;
    boolean HC,OC,FC;
    int BookCart = 0;
    int click =0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Menu = new javax.swing.JPanel();
        HomeButton2 = new javax.swing.JButton();
        HOMEPanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        SELLButton = new javax.swing.JButton();
        SELLPanel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        AddButton1 = new javax.swing.JButton();
        AddPanel = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        STOCKButton = new javax.swing.JButton();
        STOCKPanel = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        Background = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Tab = new javax.swing.JTabbedPane();
        Home = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        kButton20 = new com.k33ptoo.components.KButton();
        kButton19 = new com.k33ptoo.components.KButton();
        kButton13 = new com.k33ptoo.components.KButton();
        jPanel3 = new javax.swing.JPanel();
        Sell = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        BookSell = new javax.swing.JTextField();
        kButton8 = new com.k33ptoo.components.KButton();
        ProductSell = new javax.swing.JTextField();
        kButton9 = new com.k33ptoo.components.KButton();
        CartPanel = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        kButton10 = new com.k33ptoo.components.KButton();
        TotalPrice = new javax.swing.JLabel();
        kButton12 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        Cart = new javax.swing.JButton();
        kButton11 = new com.k33ptoo.components.KButton();
        AddBook = new javax.swing.JPanel();
        AddTab = new javax.swing.JTabbedPane();
        AddToStock = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        ProductAdd = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        BookAdd = new javax.swing.JTextField();
        kButton5 = new com.k33ptoo.components.KButton();
        kButton6 = new com.k33ptoo.components.KButton();
        kButton18 = new com.k33ptoo.components.KButton();
        kButton17 = new com.k33ptoo.components.KButton();
        AddNewBook = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        AmountAdd = new javax.swing.JTextField();
        NameAdd = new javax.swing.JTextField();
        VolumeAdd = new javax.swing.JTextField();
        PriceAdd = new javax.swing.JTextField();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        jLabel17 = new javax.swing.JLabel();
        KeywordAdd = new javax.swing.JTextField();
        RatedAdd = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        LanguageAdd = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        kButton16 = new com.k33ptoo.components.KButton();
        kButton15 = new com.k33ptoo.components.KButton();
        Stock = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        AmountList = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        PriceList = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        NameList = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        ProductCodeList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton14 = new com.k33ptoo.components.KButton();
        kButton22 = new com.k33ptoo.components.KButton();
        kButton21 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1250, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/Logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(1, 177, 196));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/Exit.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/Exit2.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 60));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeButton2.setBackground(new java.awt.Color(4, 126, 165));
        HomeButton2.setFont(new java.awt.Font("Leelawadee UI", 0, 22)); // NOI18N
        HomeButton2.setForeground(new java.awt.Color(255, 255, 255));
        HomeButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/house.png"))); // NOI18N
        HomeButton2.setText(" HOME         ");
        HomeButton2.setBorderPainted(false);
        HomeButton2.setContentAreaFilled(false);
        HomeButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeButton2MouseExited(evt);
            }
        });
        HomeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButton2ActionPerformed(evt);
            }
        });
        Menu.add(HomeButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, 100));

        HOMEPanel.setBackground(new java.awt.Color(5, 124, 165));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setForeground(new java.awt.Color(5, 124, 165));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HOMEPanelLayout = new javax.swing.GroupLayout(HOMEPanel);
        HOMEPanel.setLayout(HOMEPanelLayout);
        HOMEPanelLayout.setHorizontalGroup(
            HOMEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HOMEPanelLayout.createSequentialGroup()
                .addGap(0, 221, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HOMEPanelLayout.setVerticalGroup(
            HOMEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Menu.add(HOMEPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));
        HOMEPanel.setVisible(false);

        SELLButton.setBackground(new java.awt.Color(4, 126, 165));
        SELLButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        SELLButton.setForeground(new java.awt.Color(255, 255, 255));
        SELLButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/Sell.png"))); // NOI18N
        SELLButton.setText("  SELL       ");
        SELLButton.setBorderPainted(false);
        SELLButton.setContentAreaFilled(false);
        SELLButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SELLButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SELLButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SELLButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SELLButtonMouseExited(evt);
            }
        });
        SELLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELLButtonActionPerformed(evt);
            }
        });
        SELLPanel.setVisible(false);
        Menu.add(SELLButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 250, 260, 100));

        SELLPanel.setBackground(new java.awt.Color(5, 124, 165));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setForeground(new java.awt.Color(5, 124, 165));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SELLPanelLayout = new javax.swing.GroupLayout(SELLPanel);
        SELLPanel.setLayout(SELLPanelLayout);
        SELLPanelLayout.setHorizontalGroup(
            SELLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SELLPanelLayout.createSequentialGroup()
                .addGap(0, 221, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SELLPanelLayout.setVerticalGroup(
            SELLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Menu.add(SELLPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));
        HOMEPanel.setVisible(false);

        AddButton1.setBackground(new java.awt.Color(4, 126, 165));
        AddButton1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        AddButton1.setForeground(new java.awt.Color(255, 255, 255));
        AddButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/Addicon.png"))); // NOI18N
        AddButton1.setText("  ADD");
        AddButton1.setBorderPainted(false);
        AddButton1.setContentAreaFilled(false);
        AddButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddButton1MouseExited(evt);
            }
        });
        AddButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButton1ActionPerformed(evt);
            }
        });
        SELLPanel.setVisible(false);
        Menu.add(AddButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 370, 290, 100));

        AddPanel.setBackground(new java.awt.Color(5, 124, 165));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setForeground(new java.awt.Color(5, 124, 165));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AddPanelLayout = new javax.swing.GroupLayout(AddPanel);
        AddPanel.setLayout(AddPanelLayout);
        AddPanelLayout.setHorizontalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPanelLayout.createSequentialGroup()
                .addGap(0, 221, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AddPanelLayout.setVerticalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Menu.add(AddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, -1));
        AddPanel.setVisible(false);

        STOCKButton.setBackground(new java.awt.Color(4, 126, 165));
        STOCKButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 22)); // NOI18N
        STOCKButton.setForeground(new java.awt.Color(255, 255, 255));
        STOCKButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/Stock.png"))); // NOI18N
        STOCKButton.setText(" BOOK STOCK");
        STOCKButton.setBorderPainted(false);
        STOCKButton.setContentAreaFilled(false);
        STOCKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                STOCKButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                STOCKButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                STOCKButtonMouseExited(evt);
            }
        });
        STOCKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STOCKButtonActionPerformed(evt);
            }
        });
        STOCKPanel.setVisible(false);
        Menu.add(STOCKButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 490, 300, 100));

        STOCKPanel.setBackground(new java.awt.Color(5, 124, 165));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setForeground(new java.awt.Color(5, 124, 165));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout STOCKPanelLayout = new javax.swing.GroupLayout(STOCKPanel);
        STOCKPanel.setLayout(STOCKPanelLayout);
        STOCKPanelLayout.setHorizontalGroup(
            STOCKPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, STOCKPanelLayout.createSequentialGroup()
                .addGap(0, 221, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        STOCKPanelLayout.setVerticalGroup(
            STOCKPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Menu.add(STOCKPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 230, -1));
        HOMEPanel.setVisible(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/BackGround.png"))); // NOI18N
        Background.setToolTipText("");
        Background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 640));

        jPanel2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, 640));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1280, 90));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, -20, 50, 760));

        Tab.setBackground(new java.awt.Color(255, 255, 255));
        Tab.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        Tab.setToolTipText("");

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setPreferredSize(new java.awt.Dimension(1280, 720));
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(102, 204, 255));
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/BIGLOGO.png"))); // NOI18N
        Home.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 340, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/Poster.png"))); // NOI18N
        Home.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 260, 390));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel1.setText("Developer");
        Home.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, 20));

        jLabel3.setText("Pakin Suwannop");
        Home.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, 40));

        jLabel6.setText("Paritipat Insumran");
        Home.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, 40));

        jLabel7.setText("Group zero");
        Home.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, 20));

        jLabel8.setText("Kasetsart University");
        Home.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, 40));
        Home.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 640, 30));

        kButton20.setBackground(new java.awt.Color(249, 250, 254));
        kButton20.setBorder(null);
        kButton20.setForeground(new java.awt.Color(249, 250, 254));
        kButton20.setkAllowGradient(false);
        kButton20.setkBackGroundColor(new java.awt.Color(34, 37, 41));
        kButton20.setkBorderRadius(50);
        kButton20.setkEndColor(new java.awt.Color(34, 37, 41));
        kButton20.setkForeGround(new java.awt.Color(51, 51, 51));
        kButton20.setkHoverColor(new java.awt.Color(34, 37, 41));
        kButton20.setkHoverEndColor(new java.awt.Color(34, 37, 41));
        kButton20.setkHoverForeGround(new java.awt.Color(34, 37, 41));
        kButton20.setkHoverStartColor(new java.awt.Color(34, 37, 41));
        kButton20.setkIndicatorColor(new java.awt.Color(34, 37, 41));
        kButton20.setkPressedColor(new java.awt.Color(34, 37, 41));
        kButton20.setkSelectedColor(new java.awt.Color(5, 124, 165));
        kButton20.setkStartColor(new java.awt.Color(34, 37, 41));
        kButton20.setSelected(true);
        kButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton20ActionPerformed(evt);
            }
        });
        Home.add(kButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 420, 140));

        kButton19.setBackground(new java.awt.Color(249, 250, 254));
        kButton19.setBorder(null);
        kButton19.setForeground(new java.awt.Color(249, 250, 254));
        kButton19.setkAllowGradient(false);
        kButton19.setkBackGroundColor(new java.awt.Color(34, 37, 41));
        kButton19.setkBorderRadius(50);
        kButton19.setkEndColor(new java.awt.Color(34, 37, 41));
        kButton19.setkForeGround(new java.awt.Color(51, 51, 51));
        kButton19.setkHoverColor(new java.awt.Color(34, 37, 41));
        kButton19.setkHoverEndColor(new java.awt.Color(34, 37, 41));
        kButton19.setkHoverForeGround(new java.awt.Color(34, 37, 41));
        kButton19.setkHoverStartColor(new java.awt.Color(34, 37, 41));
        kButton19.setkIndicatorColor(new java.awt.Color(34, 37, 41));
        kButton19.setkPressedColor(new java.awt.Color(34, 37, 41));
        kButton19.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton19.setkStartColor(new java.awt.Color(34, 37, 41));
        kButton19.setSelected(true);
        kButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton19ActionPerformed(evt);
            }
        });
        Home.add(kButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 630, 490));

        kButton13.setBackground(new java.awt.Color(249, 250, 254));
        kButton13.setBorder(null);
        kButton13.setForeground(new java.awt.Color(249, 250, 254));
        kButton13.setkAllowGradient(false);
        kButton13.setkBackGroundColor(new java.awt.Color(34, 37, 41));
        kButton13.setkBorderRadius(50);
        kButton13.setkEndColor(new java.awt.Color(34, 37, 41));
        kButton13.setkForeGround(new java.awt.Color(51, 51, 51));
        kButton13.setkHoverColor(new java.awt.Color(34, 37, 41));
        kButton13.setkHoverEndColor(new java.awt.Color(34, 37, 41));
        kButton13.setkHoverForeGround(new java.awt.Color(34, 37, 41));
        kButton13.setkHoverStartColor(new java.awt.Color(34, 37, 41));
        kButton13.setkIndicatorColor(new java.awt.Color(34, 37, 41));
        kButton13.setkPressedColor(new java.awt.Color(34, 37, 41));
        kButton13.setkSelectedColor(new java.awt.Color(244, 246, 249));
        kButton13.setkStartColor(new java.awt.Color(34, 37, 41));
        kButton13.setSelected(true);
        kButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton13ActionPerformed(evt);
            }
        });
        Home.add(kButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 940, 540));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        Home.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, -180, 60, -1));

        Tab.addTab("tab1", Home);

        Sell.setBackground(new java.awt.Color(244, 246, 249));
        Sell.setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel9.setBackground(new java.awt.Color(244, 246, 249));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(96, 208, 217));
        jLabel28.setText("SELL");
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel29.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(120, 222, 238));
        jLabel29.setText("Product Code");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 30));

        jLabel30.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(120, 222, 238));
        jLabel30.setText("Amount");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, 30));
        jPanel9.add(BookSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 400, 30));

        kButton8.setBorder(null);
        kButton8.setText("Clear");
        kButton8.setkBorderRadius(40);
        kButton8.setkEndColor(new java.awt.Color(21, 117, 220));
        kButton8.setkHoverEndColor(new java.awt.Color(21, 95, 211));
        kButton8.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton8.setkHoverStartColor(new java.awt.Color(0, 159, 186));
        kButton8.setkPressedColor(new java.awt.Color(0, 130, 161));
        kButton8.setkSelectedColor(new java.awt.Color(0, 161, 189));
        kButton8.setkStartColor(new java.awt.Color(0, 179, 195));
        kButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton8MouseClicked(evt);
            }
        });
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });
        jPanel9.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        ProductSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductSellActionPerformed(evt);
            }
        });
        jPanel9.add(ProductSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 400, 30));

        kButton9.setBorder(null);
        kButton9.setText("Add to cart");
        kButton9.setkBorderRadius(40);
        kButton9.setkEndColor(new java.awt.Color(163, 43, 255));
        kButton9.setkHoverEndColor(new java.awt.Color(21, 95, 211));
        kButton9.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton9.setkHoverStartColor(new java.awt.Color(0, 159, 186));
        kButton9.setkPressedColor(new java.awt.Color(0, 130, 161));
        kButton9.setkSelectedColor(new java.awt.Color(0, 161, 189));
        kButton9.setkStartColor(new java.awt.Color(22, 187, 255));
        kButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton9MouseClicked(evt);
            }
        });
        jPanel9.add(kButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        CartPanel.setBackground(new java.awt.Color(255, 255, 255));
        CartPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 255));
        jLabel31.setText("Cart");
        CartPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 70, 30));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Amount");
        CartPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, 50));

        jList7.setBorder(null);
        jList7.setSelectionBackground(new java.awt.Color(2, 175, 197));
        jList7.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(jList7);

        CartPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 170, 390));

        jList6.setBorder(null);
        jList6.setSelectionBackground(new java.awt.Color(2, 175, 197));
        jList6.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jList6);

        CartPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, 390));

        kButton10.setBorder(null);
        kButton10.setText("Checkout");
        kButton10.setkAllowGradient(false);
        kButton10.setkBackGroundColor(new java.awt.Color(242, 196, 10));
        kButton10.setkBorderRadius(40);
        kButton10.setkHoverColor(new java.awt.Color(242, 179, 22));
        kButton10.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton10.setkHoverStartColor(new java.awt.Color(242, 196, 10));
        kButton10.setkPressedColor(new java.awt.Color(242, 161, 16));
        kButton10.setkSelectedColor(new java.awt.Color(242, 161, 16));
        kButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton10MouseClicked(evt);
            }
        });
        CartPanel.add(kButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 110, 40));

        TotalPrice.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        TotalPrice.setForeground(new java.awt.Color(0, 153, 204));
        TotalPrice.setText("Total Price = 0");
        CartPanel.add(TotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 100, 35));

        kButton12.setkBorderRadius(30);
        kButton12.setkSelectedColor(new java.awt.Color(248, 253, 254));
        kButton12.setSelected(true);
        CartPanel.add(kButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, 490));

        kButton7.setBackground(new java.awt.Color(248, 253, 254));
        kButton7.setBorder(null);
        kButton7.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        kButton7.setkBorderRadius(50);
        kButton7.setkEndColor(new java.awt.Color(21, 117, 220));
        kButton7.setkIndicatorThickness(50);
        kButton7.setkSelectedColor(new java.awt.Color(248, 253, 254));
        kButton7.setkStartColor(new java.awt.Color(0, 179, 195));
        CartPanel.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 370, 530));

        jPanel9.add(CartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 380, 530));
        CartPanel.setVisible(false);

        Cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/Cart.png"))); // NOI18N
        Cart.setText("    0");
        Cart.setBorder(null);
        Cart.setBorderPainted(false);
        Cart.setContentAreaFilled(false);
        Cart.setFocusPainted(false);
        Cart.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/Cart2.png"))); // NOI18N
        Cart.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/Cart3.png"))); // NOI18N
        Cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartMouseClicked(evt);
            }
        });
        Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartActionPerformed(evt);
            }
        });
        jPanel9.add(Cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 110, 40));

        kButton11.setText("kButton11");
        kButton11.setToolTipText("");
        kButton11.setkBackGroundColor(new java.awt.Color(19, 49, 85));
        kButton11.setkBorderRadius(50);
        kButton11.setkEndColor(new java.awt.Color(22, 29, 55));
        kButton11.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton11.setkStartColor(new java.awt.Color(19, 49, 85));
        kButton11.setSelected(true);
        jPanel9.add(kButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 980, 550));

        javax.swing.GroupLayout SellLayout = new javax.swing.GroupLayout(Sell);
        Sell.setLayout(SellLayout);
        SellLayout.setHorizontalGroup(
            SellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );
        SellLayout.setVerticalGroup(
            SellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab.addTab("tab1", Sell);

        AddBook.setBackground(new java.awt.Color(244, 246, 249));
        AddBook.setMinimumSize(new java.awt.Dimension(1000, 720));
        AddBook.setName(""); // NOI18N
        AddBook.setPreferredSize(new java.awt.Dimension(1280, 720));
        AddBook.setLayout(null);

        AddTab.setBackground(new java.awt.Color(23, 110, 223));
        AddTab.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        AddToStock.setBackground(new java.awt.Color(255, 255, 255));
        AddToStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(96, 208, 217));
        jLabel21.setText("ADD BOOK IN STOCK");
        AddToStock.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel22.setText("Product Code");
        AddToStock.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 125, -1));

        ProductAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductAddActionPerformed(evt);
            }
        });
        AddToStock.add(ProductAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 405, 30));

        jLabel23.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel23.setText("Amount");
        AddToStock.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 125, -1));
        AddToStock.add(BookAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 405, 30));

        kButton5.setText("Confirm");
        kButton5.setkBorderRadius(20);
        kButton5.setkEndColor(new java.awt.Color(21, 117, 220));
        kButton5.setkHoverEndColor(new java.awt.Color(21, 95, 211));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton5.setkHoverStartColor(new java.awt.Color(0, 159, 186));
        kButton5.setkPressedColor(new java.awt.Color(0, 130, 161));
        kButton5.setkSelectedColor(new java.awt.Color(0, 161, 189));
        kButton5.setkStartColor(new java.awt.Color(0, 179, 195));
        kButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton5MouseClicked(evt);
            }
        });
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });
        AddToStock.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        kButton6.setText("Clear");
        kButton6.setkEndColor(new java.awt.Color(21, 117, 220));
        kButton6.setkHoverEndColor(new java.awt.Color(21, 95, 211));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton6.setkHoverStartColor(new java.awt.Color(0, 159, 186));
        kButton6.setkPressedColor(new java.awt.Color(0, 130, 161));
        kButton6.setkSelectedColor(new java.awt.Color(0, 161, 189));
        kButton6.setkStartColor(new java.awt.Color(0, 179, 195));
        kButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton6MouseClicked(evt);
            }
        });
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });
        AddToStock.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        kButton18.setkBorderRadius(50);
        kButton18.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton18.setSelected(true);
        AddToStock.add(kButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 840, 420));

        kButton17.setkBorderRadius(50);
        kButton17.setkSelectedColor(new java.awt.Color(244, 246, 249));
        kButton17.setSelected(true);
        AddToStock.add(kButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 950, 540));

        AddTab.addTab("Add book in stock", AddToStock);

        AddNewBook.setBackground(new java.awt.Color(255, 255, 255));
        AddNewBook.setMinimumSize(new java.awt.Dimension(1000, 600));
        AddNewBook.setPreferredSize(new java.awt.Dimension(1000, 600));
        AddNewBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel12.setText("Category");
        AddNewBook.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 120, 40));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select Category","Manga", "Light Novel", "Novel", "Comic" , "Tale" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        AddNewBook.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 220, -1));

        jLabel13.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel13.setText("Amount");
        AddNewBook.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel14.setText("Name of book");
        AddNewBook.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel15.setText("Volume");
        AddNewBook.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 285, -1, 30));

        jLabel16.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel16.setText("Price");
        AddNewBook.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));
        AddNewBook.add(AmountAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 290, 30));

        NameAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameAddActionPerformed(evt);
            }
        });
        AddNewBook.add(NameAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 390, 30));

        VolumeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeAddActionPerformed(evt);
            }
        });
        AddNewBook.add(VolumeAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 170, 30));
        AddNewBook.add(PriceAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 290, 30));

        kButton3.setText("Confirm");
        kButton3.setkBorderRadius(40);
        kButton3.setkEndColor(new java.awt.Color(21, 117, 220));
        kButton3.setkHoverEndColor(new java.awt.Color(21, 95, 211));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 159, 186));
        kButton3.setkPressedColor(new java.awt.Color(0, 130, 161));
        kButton3.setkSelectedColor(new java.awt.Color(0, 161, 189));
        kButton3.setkStartColor(new java.awt.Color(0, 179, 195));
        kButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton3MouseClicked(evt);
            }
        });
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        AddNewBook.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        kButton4.setBorder(null);
        kButton4.setText("Clear");
        kButton4.setkBorderRadius(40);
        kButton4.setkEndColor(new java.awt.Color(21, 117, 220));
        kButton4.setkHoverEndColor(new java.awt.Color(21, 95, 211));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverStartColor(new java.awt.Color(0, 159, 186));
        kButton4.setkPressedColor(new java.awt.Color(0, 130, 161));
        kButton4.setkSelectedColor(new java.awt.Color(0, 161, 189));
        kButton4.setkStartColor(new java.awt.Color(0, 179, 195));
        kButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton4MouseClicked(evt);
            }
        });
        AddNewBook.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        jLabel17.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel17.setText("Keyword of Book ( example OP = Onepice)");
        AddNewBook.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        KeywordAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeywordAddActionPerformed(evt);
            }
        });
        AddNewBook.add(KeywordAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 390, 30));

        RatedAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatedAddActionPerformed(evt);
            }
        });
        AddNewBook.add(RatedAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 180, 30));
        RatedAdd.setVisible(false);

        jLabel18.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel18.setText("Rated");
        AddNewBook.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));
        jLabel18.setVisible(false);

        jLabel19.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel19.setText("Language");
        AddNewBook.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));
        jLabel19.setVisible(false);

        LanguageAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanguageAddActionPerformed(evt);
            }
        });
        AddNewBook.add(LanguageAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 160, 30));
        LanguageAdd.setVisible(false);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphic/Nessie.gif"))); // NOI18N
        AddNewBook.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 310, 140, 130));

        jLabel20.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(96, 208, 217));
        jLabel20.setText("ADD NEW BOOK");
        AddNewBook.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        kButton16.setkBorderRadius(50);
        kButton16.setkSelectedColor(new java.awt.Color(255, 255, 255));
        kButton16.setSelected(true);
        AddNewBook.add(kButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 840, 400));

        kButton15.setkBorderRadius(50);
        kButton15.setkSelectedColor(new java.awt.Color(244, 246, 249));
        kButton15.setSelected(true);
        AddNewBook.add(kButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 960, 500));

        AddTab.addTab("Add new book", AddNewBook);

        AddBook.add(AddTab);
        AddTab.setBounds(0, 0, 1000, 633);

        Tab.addTab("tab1", AddBook);

        Stock.setBackground(new java.awt.Color(255, 255, 255));
        Stock.setPreferredSize(new java.awt.Dimension(1280, 720));
        Stock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(96, 208, 217));
        jLabel11.setText("BOOK STOCK");
        Stock.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 40));

        jList4.setModel(new javax.swing.AbstractListModel<Integer>() {
            Integer[] strings = Sorting.showAmount();
            public int getSize() { return strings.length; }
            public Integer getElementAt(int i) { return strings[i]; }
        });
        NameList.setVerticalScrollBar(PriceList.getVerticalScrollBar());
        ProductCodeList.setVerticalScrollBar(PriceList.getVerticalScrollBar());
        AmountList.setVerticalScrollBar(PriceList.getVerticalScrollBar());
        AmountList.setViewportView(jList4);

        Stock.add(AmountList, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 210, 340));

        jList3.setModel(new javax.swing.AbstractListModel<Integer>() {
            Integer[] strings = Sorting.showPrice();
            public int getSize() { return strings.length; }
            public Integer getElementAt(int i) { return strings[i]; }
        });
        PriceList.setViewportView(jList3);

        Stock.add(PriceList, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 224, 340));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = Sorting.showName();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        NameList.setViewportView(jList2);

        Stock.add(NameList, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 224, 340));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = Sorting.showProductCode();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ProductCodeList.setViewportView(jList1);

        Stock.add(ProductCodeList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 224, 340));

        jLabel24.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Product Code ");
        Stock.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 100, 110, -1));

        jLabel25.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Book Name");
        Stock.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 100, 90, -1));

        jLabel26.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Book Price");
        Stock.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 100, 90, -1));

        jLabel27.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Amount");
        Stock.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 100, 80, -1));

        kButton2.setBackground(new java.awt.Color(23, 110, 223));
        kButton2.setForeground(new java.awt.Color(23, 110, 223));
        kButton2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        kButton2.setkAllowGradient(false);
        kButton2.setkHoverColor(new java.awt.Color(164, 164, 252));
        kButton2.setkSelectedColor(new java.awt.Color(23, 110, 223));
        kButton2.setSelected(true);
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        Stock.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 870, -1));

        kButton1.setBorder(null);
        kButton1.setText("Update Data");
        kButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        kButton1.setkBorderRadius(40);
        kButton1.setkEndColor(new java.awt.Color(21, 117, 220));
        kButton1.setkHoverEndColor(new java.awt.Color(21, 95, 211));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton1.setkIndicatorColor(new java.awt.Color(0, 153, 153));
        kButton1.setkPressedColor(new java.awt.Color(0, 99, 138));

        kButton1.setkSelectedColor(new java.awt.Color(0, 107, 151));

        kButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton1MouseClicked(evt);
            }
        });
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        Stock.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, -1, -1));

        kButton14.setBackground(new java.awt.Color(249, 250, 254));
        kButton14.setBorder(null);
        kButton14.setForeground(new java.awt.Color(249, 250, 254));
        kButton14.setkAllowGradient(false);
        kButton14.setkBackGroundColor(new java.awt.Color(34, 37, 41));
        kButton14.setkBorderRadius(50);
        kButton14.setkEndColor(new java.awt.Color(34, 37, 41));
        kButton14.setkForeGround(new java.awt.Color(51, 51, 51));
        kButton14.setkHoverColor(new java.awt.Color(34, 37, 41));
        kButton14.setkHoverEndColor(new java.awt.Color(34, 37, 41));
        kButton14.setkHoverForeGround(new java.awt.Color(34, 37, 41));
        kButton14.setkHoverStartColor(new java.awt.Color(34, 37, 41));
        kButton14.setkIndicatorColor(new java.awt.Color(34, 37, 41));
        kButton14.setkPressedColor(new java.awt.Color(34, 37, 41));
        kButton14.setkSelectedColor(new java.awt.Color(249, 250, 254));
        kButton14.setkStartColor(new java.awt.Color(34, 37, 41));
        kButton14.setSelected(true);
        kButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton14ActionPerformed(evt);
            }
        });
        Stock.add(kButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 940, 540));

        Tab.addTab("tab1", Stock);

        jPanel2.add(Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 1070, 600));
        Tab.getAccessibleContext().setAccessibleName("Tab");

        kButton22.setBackground(new java.awt.Color(102, 102, 255));
        kButton22.setForeground(new java.awt.Color(51, 102, 255));
        kButton22.setText("Add Book in Stock");
        kButton22.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        kButton22.setkAllowGradient(false);
        kButton22.setkBackGroundColor(new java.awt.Color(244, 246, 249));
        kButton22.setkBorderRadius(30);
        kButton22.setkForeGround(new java.awt.Color(23, 110, 223));
        kButton22.setkHoverColor(new java.awt.Color(23, 169, 228));
        kButton22.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton22.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton22.setkPressedColor(new java.awt.Color(40, 95, 166));
        kButton22.setkSelectedColor(new java.awt.Color(23, 110, 223));
        kButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton22MouseClicked(evt);
            }
        });
        jPanel2.add(kButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 120, 50));
        kButton22.setVisible(false);

        kButton21.setBackground(new java.awt.Color(102, 102, 255));
        kButton21.setForeground(new java.awt.Color(51, 102, 255));
        kButton21.setText("Add New Book");
        kButton21.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        kButton21.setkAllowGradient(false);
        kButton21.setkBackGroundColor(new java.awt.Color(244, 246, 249));
        kButton21.setkBorderRadius(30);
        kButton21.setkForeGround(new java.awt.Color(23, 110, 223));
        kButton21.setkHoverColor(new java.awt.Color(23, 169, 228));
        kButton21.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton21.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton21.setkPressedColor(new java.awt.Color(40, 95, 166));
        kButton21.setkSelectedColor(new java.awt.Color(23, 110, 223));
        kButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton21MouseClicked(evt);
            }
        });
        jPanel2.add(kButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 120, 50));
        kButton21.setVisible(false);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 730));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButton2MouseEntered
        HOMEPanel.setVisible(true);
    }//GEN-LAST:event_HomeButton2MouseEntered

    private void HomeButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButton2MouseExited
        HOMEPanel.setVisible(false);
    }//GEN-LAST:event_HomeButton2MouseExited

    private void HomeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButton2ActionPerformed

    private void SELLButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SELLButtonMouseEntered
        SELLPanel.setVisible(true);
    }//GEN-LAST:event_SELLButtonMouseEntered

    private void SELLButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SELLButtonMouseExited
        SELLPanel.setVisible(false);
    }//GEN-LAST:event_SELLButtonMouseExited

    private void SELLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELLButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SELLButtonActionPerformed

    private void STOCKButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STOCKButtonMouseEntered
        STOCKPanel.setVisible(true);
    }//GEN-LAST:event_STOCKButtonMouseEntered

    private void STOCKButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STOCKButtonMouseExited
        STOCKPanel.setVisible(false);
    }//GEN-LAST:event_STOCKButtonMouseExited

    private void STOCKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STOCKButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STOCKButtonActionPerformed

    private void HomeButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButton2MouseClicked
        Tab.setSelectedIndex(0);
        kButton21.setVisible(false);
        kButton22.setVisible(false);
        
    }//GEN-LAST:event_HomeButton2MouseClicked

    private void SELLButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SELLButtonMouseClicked
        Tab.setSelectedIndex(1);
        kButton21.setVisible(false);
        kButton22.setVisible(false);
    }//GEN-LAST:event_SELLButtonMouseClicked

    private void STOCKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STOCKButtonMouseClicked
        Tab.setSelectedIndex(3);
        kButton21.setVisible(false);
        kButton22.setVisible(false);
    }//GEN-LAST:event_STOCKButtonMouseClicked

    private void kButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton13ActionPerformed

    private void kButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton14ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed
    int x = 230;
    int a = 0;
    int posx = 260;
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
   
        if ( x == 230 ) {
            Menu.setSize(230,640);
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        
                        for ( int i = 230; i >= 0; i--){
                            Thread.sleep(1);
                            Menu.setSize(i, 640);
                            a++;
                        }
                        
                    } catch (Exception e) {
                        System.out.println("Error");
                    }
                }
            };th.start();
            x=0;
        } else if( x == 0 ){
            Menu.setSize(x, 640);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try {
                        for (int i = 0; i <= x; i++){
                            Thread.sleep(1);
                            Menu.setSize(i, 640);
                        }
                    } catch (Exception e) {
                        System.out.println("Error");
                    }
                }
            };th.start();
            x = 230;
        }
         
         
                             //Change Location of tab
         if ( posx == 260 ) {
           // Tab.setLocation(200,100);
            
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        
                        for ( int i = 260; i >= 180; i--){
                            Thread.sleep(1);
                            Tab.setLocation(i,100);
                            a++;
                        }
                        
                    } catch (Exception e) {
                        System.out.println("Error");
                    }
                }
            };th.start();
            posx=180;
                         
        } else if( posx == 180 ){
           // Tab.setLocation(260,100);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try {
                        for (int i = 180; i <= posx; i++){
                            Thread.sleep(1);
                            Tab.setLocation(i,100);
                        }
                    } catch (Exception e) {
                        System.out.println("Error");
                    }
                }
            };th.start();
            posx = 260;
            
        }
         
    }//GEN-LAST:event_jButton1MouseClicked

    private void AddButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton1MouseClicked
      Tab.setSelectedIndex(2);
      kButton21.setVisible(true);
      kButton22.setVisible(true);
    }//GEN-LAST:event_AddButton1MouseClicked

    private void AddButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton1MouseEntered
        AddPanel.setVisible(true);
        
    }//GEN-LAST:event_AddButton1MouseEntered

    private void AddButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton1MouseExited
        AddPanel.setVisible(false);
    }//GEN-LAST:event_AddButton1MouseExited

    private void AddButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButton1ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        
        
    }//GEN-LAST:event_kButton3ActionPerformed

    private void NameAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameAddActionPerformed
        
    }//GEN-LAST:event_NameAddActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        String Selected = jComboBox1.getSelectedItem().toString();
       
                    if (Selected == "Please Select Category"){
                        
                        RatedAdd.setVisible(false);
                        jLabel18.setVisible(false);
                        LanguageAdd.setVisible(false);
                        jLabel19.setVisible(false);
                    }
                    
                    else if (Selected == "Manga"){                       
                        
                        RatedAdd.setVisible(true);
                        jLabel18.setVisible(true);
                        LanguageAdd.setVisible(false);
                        jLabel19.setVisible(false);}// Manga  
                    
                    else if (Selected == "Light Novel"){                                   
                       
                        RatedAdd.setVisible(true);
                        jLabel18.setVisible(true);
                        LanguageAdd.setVisible(false);
                        jLabel19.setVisible(false);}// Light Novel
                    
                    else if (Selected == "Novel"){                       
                       
                        RatedAdd.setVisible(true);
                        jLabel18.setVisible(true);
                        LanguageAdd.setVisible(false);
                        jLabel19.setVisible(false);} // addNovel
                    
                    else if (Selected == "Comic"){
                        
                        RatedAdd.setVisible(false);
                        jLabel18.setVisible(false);
                        LanguageAdd.setVisible(false);
                        jLabel19.setVisible(false);} // Comic
                    
                    else if (Selected == "Tale"){ 
                       
                        RatedAdd.setVisible(false);
                        jLabel18.setVisible(false);
                        LanguageAdd.setVisible(true);
                        jLabel19.setVisible(true);} // Tale               
                     
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void VolumeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeAddActionPerformed
        
                  
    }//GEN-LAST:event_VolumeAddActionPerformed

    private void KeywordAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeywordAddActionPerformed
                   
    }//GEN-LAST:event_KeywordAddActionPerformed

    private void RatedAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatedAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RatedAddActionPerformed

    
    private void kButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton3MouseClicked
       
            
        String Selected = jComboBox1.getSelectedItem().toString();
            
        if (Selected == "Manga"){
            code = "34294";}
                    
        else if (Selected == "Light Novel"){
            code = "71207"; }
  
        else if (Selected == "Novel"){
            code = "20731";} // addNovel
        else if (Selected == "Comic")
             code = "40314"; // Comic
        else if (Selected == "Tale"){
            code = "74135";}
        
        name = NameAdd.getText();
        rated = Integer.parseInt(RatedAdd.getText());       
        vol = VolumeAdd.getText();  
        keyword = KeywordAdd.getText();
        String sPrice = PriceAdd.getText();
        price = Integer.parseInt(sPrice);
        String sAmount = AmountAdd.getText();  
        numOfBooks = Integer.parseInt(sAmount);
        pCode = code + keyword + vol ;    

           if(code == "34294") { // Manga
            Manga.addManga(pCode, name, price, rated,numOfBooks);               
           }
           
           else if(code == "71207") { // Light Novel 
            lightNovel.addLightNovel(pCode, name, price, rated,numOfBooks);               
           }
           
           else if(code == "20731"){ // addNovel
               Novel.addNovel(pCode, name, price, rated, numOfBooks);
           }
           
           else if(code == "40314"){ // Comic
               Comic.addComic(pCode, name, price,numOfBooks);
           }
           
           else if(code == "74135"){ // Tale 
               language = LanguageAdd.getText();
               Tale.addTale(pCode, name, price, language,numOfBooks);
           }
        String st = "New books has been add.";
        JOptionPane.showMessageDialog(null, st);    
    }//GEN-LAST:event_kButton3MouseClicked

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton1MouseClicked
        
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = Sorting.showProductCode();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = Sorting.showName();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList3.setModel(new javax.swing.AbstractListModel<Integer>() {
            Integer[] strings = Sorting.showPrice();
            public int getSize() { return strings.length; }
            public Integer getElementAt(int i) { return strings[i]; }
        });
        jList4.setModel(new javax.swing.AbstractListModel<Integer>() {
            Integer[] strings = Sorting.showAmount();
            public int getSize() { return strings.length; }
            public Integer getElementAt(int i) { return strings[i]; 
            }
        });
        
        String st = "Data Update.";
        JOptionPane.showMessageDialog(null, st);
    }//GEN-LAST:event_kButton1MouseClicked

    private void LanguageAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanguageAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LanguageAddActionPerformed

    private void kButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton4MouseClicked
        AmountAdd.setText("");        NameAdd.setText("");
        PriceAdd.setText("");        KeywordAdd.setText("");
        VolumeAdd.setText("");       LanguageAdd.setText("");
        RatedAdd.setText("");
        
    }//GEN-LAST:event_kButton4MouseClicked

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton5MouseClicked
                     String tmp = ProductAdd.getText();                    
                     int add = Integer.parseInt(BookAdd.getText()); 
                     dic.books.get(tmp).addBook(add);
                     System.out.println("Amount = " + dic.books.get(tmp).getNumOfBooks());
                     String st = "Amount of books increased.";
                     JOptionPane.showMessageDialog(null, st);
    }//GEN-LAST:event_kButton5MouseClicked

    private void ProductAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductAddActionPerformed

    private void kButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton6MouseClicked
        ProductAdd.setText("");
        BookAdd.setText("");
    }//GEN-LAST:event_kButton6MouseClicked

    private void kButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton8MouseClicked
        
        BookCart=0;
        Cart.setText("    "+BookCart);
        Arrays.fill(SellGUI.getArraySell(),null);
        Arrays.fill(SellGUI.getArrayProductCode(),null);
        Arrays.fill(SellGUI.getArrayNumBook(),null);
        SellGUI.setI(0);
        
        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {""};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        }); 
        jList7.setModel(new javax.swing.AbstractListModel<Integer>() {
            Integer[] strings = { };
            public int getSize() { return strings.length; }
            public Integer getElementAt(int i) { return strings[i]; }
        }); 
        TotalPrice.setText("Total Price = 0");
        ProductSell.setText("");
        BookSell.setText("");
        
    }//GEN-LAST:event_kButton8MouseClicked

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton8ActionPerformed

    private void ProductSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductSellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductSellActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton5ActionPerformed

    private void kButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton9MouseClicked
 
        int AmountSell = Integer.parseInt(BookSell.getText());
        BookCart+=AmountSell;
        SellGUI.addToCart(ProductSell.getText(),AmountSell);
        Cart.setText("    "+BookCart);
        String st = "Book has been add.";
        JOptionPane.showMessageDialog(null, st);
    }//GEN-LAST:event_kButton9MouseClicked

    private void CartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMouseClicked
  
    if(click==0){
    CartPanel.setVisible(true);
    click++;
    }
    else if(click == 1){
    CartPanel.setVisible(false);
    click=0;
    }
    
    
    jList6.setModel(new javax.swing.AbstractListModel<String>() {
    String[] strings = SellGUI.getArraySell();
        public int getSize() { return SellGUI.getI(); }
        public String getElementAt(int i) { return strings[i]; }
    });
    
    jList7.setModel(new javax.swing.AbstractListModel<Integer>() {
        Integer[] arrInt = SellGUI.getArrayNumBook();
        public int getSize() { return SellGUI.getI(); }
        public Integer getElementAt(int i) { return arrInt[i]; }
    });
    
    int totalPrice = SellGUI.totalPrice();
    String StringTotalPrice = Integer.toString(totalPrice);
    TotalPrice.setText("Total Price = "+StringTotalPrice);
    
    
    }//GEN-LAST:event_CartMouseClicked

    private void kButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton10MouseClicked
        SellGUI.sellInCart();
        BookCart=0;
        Cart.setText("    "+BookCart);
        String[] a ={"a","a"};
        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { ""};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        }); 
        jList7.setModel(new javax.swing.AbstractListModel<Integer>() {
            Integer[] strings = { };
            public int getSize() { return strings.length; }
            public Integer getElementAt(int i) { return strings[i]; }
        }); 
        TotalPrice.setText("Total Price = 0");
        
        
    }//GEN-LAST:event_kButton10MouseClicked

    private void kButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton19ActionPerformed

    private void kButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton20ActionPerformed

    private void kButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton21MouseClicked
        AddTab.setSelectedIndex(1);
    
    }//GEN-LAST:event_kButton21MouseClicked

    private void kButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton22MouseClicked
        AddTab.setSelectedIndex(0);

    }//GEN-LAST:event_kButton22MouseClicked

    private void CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CartActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
                FileCSV read = new FileCSV();
        read.readCSV("C:\\Users\\maMo\\Desktop\\BookStore(Back-UP)\\Bookdata.csv");

        Scanner sc = new Scanner(System.in);

        while (true) {
            System.out.println();
            System.out.println("Press");
            System.out.println("1.add new book");
            System.out.println("2.show all books");
            System.out.println("3.remove book");
            System.out.println("4.sell book");
            System.out.println("5.fill book in stock");
            System.out.println("6.Save book data");
            System.out.println();

            int num = sc.nextInt();
            sc.nextLine();
            
            switch (num) {
                case 1 -> { //add new book to stock
                    System.out.println("1.Manga");
                    System.out.println("2.Light Novel");
                    System.out.println("3.Novel");
                    System.out.println("4.Comic");
                    System.out.println("5.Tale");

                    System.out.print("Enter type of Book : ");}
 
                case 2 -> { //Show all book
                    for(int i = 0; i < Sorting.showName().length; i++) {
                        System.out.println(Sorting.showName()[i]);
                    }
                    
                }
                case 3 -> { //Remove book from data
                    System.out.println("Enter Product Code : ");
                    String tmp = sc.nextLine();
                    dic.books.remove(tmp);
                    System.out.println(tmp + " has been removed");
                }
                case 4 -> { //sell book 
                    System.out.println("Enter Product Code : ");
                    String tmp = sc.nextLine();
                    int sell = sc.nextInt();
                    dic.books.get(tmp).sellBook(sell);
                    System.out.println("Book has been sold.");
                    System.out.println("Amount = " + dic.books.get(tmp).getNumOfBooks());
                    System.out.println();
                }
                case 5 -> { //add book in stock
                    System.out.println("Enter Product Code : ");
                    String tmp = sc.nextLine();
                    System.out.println("Amount : ");
                    int add = sc.nextInt();
                    dic.books.get(tmp).addBook(add);
                    System.out.println("Book has been increaced.");
                    System.out.println("Amount = " + dic.books.get(tmp).getNumOfBooks());
                    System.out.println();
                }
                case 6 -> { //save data of book
                    // FileCSV save = new FileCSV();
                    // save.saveCSV();
                    for(int i = 0;i<Sorting.showProductCode().length;i++){

                            String a = Sorting.showName()[i];
                            System.out.println(a);
                        }
                }
                default -> {
                }
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddBook;
    private javax.swing.JButton AddButton1;
    private javax.swing.JPanel AddNewBook;
    private javax.swing.JPanel AddPanel;
    private javax.swing.JTabbedPane AddTab;
    private javax.swing.JPanel AddToStock;
    private javax.swing.JTextField AmountAdd;
    private javax.swing.JScrollPane AmountList;
    private javax.swing.JLabel Background;
    private javax.swing.JTextField BookAdd;
    private javax.swing.JTextField BookSell;
    private javax.swing.JButton Cart;
    private javax.swing.JPanel CartPanel;
    private javax.swing.JPanel HOMEPanel;
    private javax.swing.JPanel Home;
    private javax.swing.JButton HomeButton2;
    private javax.swing.JTextField KeywordAdd;
    private javax.swing.JTextField LanguageAdd;
    private javax.swing.JPanel Menu;
    private javax.swing.JTextField NameAdd;
    private javax.swing.JScrollPane NameList;
    private javax.swing.JTextField PriceAdd;
    private javax.swing.JScrollPane PriceList;
    private javax.swing.JTextField ProductAdd;
    private javax.swing.JScrollPane ProductCodeList;
    private javax.swing.JTextField ProductSell;
    private javax.swing.JTextField RatedAdd;
    private javax.swing.JButton SELLButton;
    private javax.swing.JPanel SELLPanel;
    private javax.swing.JButton STOCKButton;
    private javax.swing.JPanel STOCKPanel;
    private javax.swing.JPanel Sell;
    private javax.swing.JPanel Stock;
    private javax.swing.JTabbedPane Tab;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TotalPrice;
    private javax.swing.JTextField VolumeAdd;
    private javax.swing.JButton jButton1;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<Integer> jList3;
    private javax.swing.JList<Integer> jList4;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<Integer> jList7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton10;
    private com.k33ptoo.components.KButton kButton11;
    private com.k33ptoo.components.KButton kButton12;
    private com.k33ptoo.components.KButton kButton13;
    private com.k33ptoo.components.KButton kButton14;
    private com.k33ptoo.components.KButton kButton15;
    private com.k33ptoo.components.KButton kButton16;
    private com.k33ptoo.components.KButton kButton17;
    private com.k33ptoo.components.KButton kButton18;
    private com.k33ptoo.components.KButton kButton19;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton20;
    private com.k33ptoo.components.KButton kButton21;
    private com.k33ptoo.components.KButton kButton22;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    private com.k33ptoo.components.KButton kButton8;
    private com.k33ptoo.components.KButton kButton9;
    // End of variables declaration//GEN-END:variables
}
